# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ReactToNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_react_native!


  # Pods for ReactToNative

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
end
